### ISSUE TITLE
Problem doing a stopVideoRecorder() on some devices

### ISSUE THREAD

**Issue by junior-ramayo** [ForgottenLight4415/flutter_background_video_recorder#1]
I/MediaRecorderJNI(27180): stop
E/MediaRecorder(27180): stop failed: -1007
E/MethodChannel#flutter_background_video_recorder(27180): Failed to handle method call
E/MethodChannel#flutter_background_video_recorder(27180): java.lang.RuntimeException: stop failed.
E/MethodChannel#flutter_background_video_recorder(27180): 	at android.media.MediaRecorder._stop(Native Method)
E/MethodChannel#flutter_background_video_recorder(27180): 	at android.media.MediaRecorder.stop(MediaRecorder.java:1399)
E/MethodChannel#flutter_background_video_recorder(27180): 	at flutter_bvr_service.VideoRecorderService.stopVideoRecording(VideoRecorderService.java:164)
E/MethodChannel#flutter_background_video_recorder(27180): 	at com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder.FlutterBackgroundVideoRecorderPlugin.onMethodCall(FlutterBackgroundVideoRecorderPlugin.java:134)
E/MethodChannel#flutter_background_video_recorder(27180): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter_background_video_recorder(27180): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_background_video_recorder(27180): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter_background_video_recorder(27180): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_background_video_recorder(27180): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter_background_video_recorder(27180): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_background_video_recorder(27180): 	at android.os.Looper.loop(Looper.java:246)
E/MethodChannel#flutter_background_video_recorder(27180): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/MethodChannel#flutter_background_video_recorder(27180): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_background_video_recorder(27180): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#flutter_background_video_recorder(27180): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/flutter (27180): PlatformException(error, stop failed., null, java.lang.RuntimeException: stop failed.
I/flutter (27180): 	at android.media.MediaRecorder._stop(Native Method)
I/flutter (27180): 	at android.media.MediaRecorder.stop(MediaRecorder.java:1399)
I/flutter (27180): 	at flutter_bvr_service.VideoRecorderService.stopVideoRecording(VideoRecorderService.java:164)
I/flutter (27180): 	at com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder.FlutterBackgroundVideoRecorderPlugin.onMethodCall(FlutterBackgroundVideoRecorderPlugin.java:134)
I/flutter (27180): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I/flutter (27180): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (27180): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
I/flutter (27180): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (27180): 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (27180): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (27180): 	at android.os.Looper.loop(Looper.java:246)
I/flutter (27180): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
I/flutter (27180): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter (27180): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
I/flutter (27180): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/flutter (27180): )

**Comment by ForgottenLight4415** [comment]
What device are you trying to run this on? What is its Android version?

**Comment by ForgottenLight4415** [comment]
What device are you trying to run this on? What is its Android version?

**Comment by junior-ramayo** [comment]
It is a Galaxy A02, One UI Core version: 3.1 and Android version: 11

**Comment by ForgottenLight4415** [comment]
Can you run the example successfully on your device?

**Comment by junior-ramayo** [comment]
The code in the example is the one I am running on the device, when I start recording everything works fine, but it is when I want to stop the recording that I get the problem

**Comment by ForgottenLight4415** [comment]
Hey! I tested the code again on Galaxy A51 running Android 13. The example is working perfectly fine on my device. Can you share the screen recording or steps to reproduce the issue?

**Comment by ForgottenLight4415** [comment]
Is your issue solved?

**Comment by ForgottenLight4415** [comment]
There is no response from you for a while. So I assume that this is no longer a problem.
