### ISSUE TITLE
crashing app 

### ISSUE THREAD

**Issue by opengits** [ForgottenLight4415/flutter_background_video_recorder#2]
Launching lib\main.dart on RMX3430 in debug mode...
Note: C:\Users\DELL\flutter_background_video_recorder-1\android\src\main\java\flutter_bvr_service\VideoRecorderService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:64679/AkU58yLW1T0=/ws
E/ion     (30448): ioctl c0044901 failed with code -1: Invalid argument
D/hw-ProcessState(30448): Binder ioctl to enable oneway spam detection failed: Invalid argument
D/SurfaceComposerClient(30448): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
E/OpenGLRenderer(30448): fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
E/OpenGLRenderer(30448): fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
D/ViewRootImpl[MainActivity](30448):  debugCancelDraw  cancelDraw=false,count = 369,android.view.ViewRootImpl@ed0f387
D/SurfaceComposerClient(30448): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
I/LightBackgroundVideoRecorder/Plugin(30448): Checking required permissions
I/LightBackgroundVideoRecorder/Plugin(30448): Permission check complete.
D/MediaRecorder(30448): constructor E 0xb400006ed5485980
D/MediaRecorder(30448): constructor X 0xb400006ed5485980
E/CheckPermission(30448): media_record-code= 24
I/LightRecordingService(30448): Target folder exists at /storage/emulated/0/Movies/Example Recorder
I/CameraManagerExtImpl(30448): getInstance success!
I/CameraManagerExtImpl(30448): packagename is com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example
I/OplusCameraManager(30448): saveOpPackageName, mOpPackageName: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example
I/OplusCameraManagerGlobal(30448): setClientInfo, packageName: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example, uid: 10044, pid: 30448
I/OplusCameraManagerGlobal(30448): Connecting to camera service
I/CameraManagerGlobal(30448): Connecting to camera service
I/OplusCameraManagerGlobal(30448): setClientInfo, packageName: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example, uid: 10044, pid: 30448
I/OplusCameraManagerGlobal(30448): setClientInfo, packageName: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example, uid: 10044, pid: 30448
I/LightRecordingService(30448): Recording service started in foreground
I/LightBackgroundVideoRecorder/Plugin(30448): Connection to service established.
I/LightRecordingService(30448): Recorder initializing
I/OplusCameraManagerGlobal(30448): setClientInfo, packageName: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example, uid: 10044, pid: 30448
I/CameraDeviceImplExtImpl(30448): getInstance success!
I/OplusCameraManagerGlobal(30448): setClientInfo, packageName: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example, uid: 10044, pid: 30448
D/OplusCameraUtils(30448): new OplusCameraUtils!
I/OplusCameraUtils(30448): current activityName: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example.MainActivity
I/OplusCameraUtils(30448): getComponentName, componentName: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example/com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example.MainActivity, packageName:com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example, activityName:com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example.MainActivity
I/CameraManager(30448): openCameraDeviceUserAsync, use componentName: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example/com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example.MainActivity
I/OplusCameraUtils(30448): current activityName: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example.MainActivity
I/OplusCameraUtils(30448): getComponentName, componentName: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example/com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example.MainActivity, packageName:com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example, activityName:com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example.MainActivity
E/Parcel  (30448): Reading a NULL string not supported here.
I/Quality (30448): SlowBinder: com.lightsoftware.flutter_background_vi to android.hardware.ICameraService cost= 111 code= 4
D/CompatibilityChangeReporter(30448): Compat change id reported: 147798919; UID 10044; state: ENABLED
I/LightBackgroundVideoRecorder/Plugin(30448): Received code INITIALIZING with message: Initializing recorder
D/MediaRecorder(30448): init E 0xb400006ed5485980
E/CheckPermission(30448): media_record-code= 2
E/CheckPermission(30448): media_record-code= 23
D/MediaRecorder(30448): init X 0xb400006ed5485980
E/CheckPermission(30448): media_record-code= 11
E/CheckPermission(30448): media_record-code= 12
E/CheckPermission(30448): media_record-code= 13
E/CheckPermission(30448): media_record-code= 20
E/CheckPermission(30448): media_record-code= 19
E/CheckPermission(30448): media_record-code= 18
E/CheckPermission(30448): media_record-code= 14
E/CheckPermission(30448): media_record-code= 15
E/CheckPermission(30448): media_record-code= 20
E/CheckPermission(30448): media_record-code= 16
D/MediaRecorder(30448): prepare E 0xb400006ed5485980
E/CheckPermission(30448): media_record-code= 9
E/MediaRecorder(30448): prepare failed: -2147483648 0xb400006ed5485980
W/System.err(30448): java.io.IOException: prepare failed.
W/System.err(30448): 	at android.media.MediaRecorder._prepare(Native Method)
W/System.err(30448): 	at android.media.MediaRecorder.prepare(MediaRecorder.java:1306)
W/System.err(30448): 	at flutter_bvr_service.VideoRecorderService.setupMediaRecorder(VideoRecorderService.java:287)
W/System.err(30448): 	at flutter_bvr_service.VideoRecorderService.startRecord(VideoRecorderService.java:232)
W/System.err(30448): 	at flutter_bvr_service.VideoRecorderService.access$100(VideoRecorderService.java:41)
W/System.err(30448): 	at flutter_bvr_service.VideoRecorderService$1.onOpened(VideoRecorderService.java:56)
W/System.err(30448): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:179)
W/System.err(30448): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(30448): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(30448): 	at android.os.Looper.loopOnce(Looper.java:233)
W/System.err(30448): 	at android.os.Looper.loop(Looper.java:344)
W/System.err(30448): 	at android.app.ActivityThread.main(ActivityThread.java:8248)
W/System.err(30448): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(30448): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
W/System.err(30448): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
D/MediaRecorder(30448): start E 0xb400006ed5485980
E/MediaRecorder(30448): start called in an invalid state: 32 0xb400006ed5485980
D/AndroidRuntime(30448): Shutting down VM
E/AndroidRuntime(30448): FATAL EXCEPTION: main
E/AndroidRuntime(30448): Process: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example, PID: 30448
E/AndroidRuntime(30448): java.lang.IllegalStateException
E/AndroidRuntime(30448): 	at android.media.MediaRecorder.start(Native Method)
E/AndroidRuntime(30448): 	at flutter_bvr_service.VideoRecorderService$1.onOpened(VideoRecorderService.java:57)
E/AndroidRuntime(30448): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:179)
E/AndroidRuntime(30448): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(30448): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30448): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(30448): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(30448): 	at android.app.ActivityThread.main(ActivityThread.java:8248)
E/AndroidRuntime(30448): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30448): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
E/AndroidRuntime(30448): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
I/Process (30448): Sending signal. PID: 30448 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by ForgottenLight4415** [comment]
Can you check if you have granted all the required permissions? Also what is your device and its Android version?

**Comment by ForgottenLight4415** [comment]
There was no reply from your side for a while. I assume the issue is now resolved. Feel free to re-open if there is any issue.
