### ISSUE TITLE
Crash - com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example, PID: 31015

### ISSUE THREAD

**Issue by user97116** [ForgottenLight4415/flutter_background_video_recorder#5]
E/AndroidRuntime(31015): FATAL EXCEPTION: main
E/AndroidRuntime(31015): Process: com.lightsoftware.flutter_background_video_recorder.flutter_background_video_recorder_example, PID: 31015
E/AndroidRuntime(31015): java.lang.IllegalStateException
E/AndroidRuntime(31015): 	at android.media.MediaRecorder.start(Native Method)
E/AndroidRuntime(31015): 	at services.VideoRecorderService$1.onOpened(VideoRecorderService.java:57)
E/AndroidRuntime(31015): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:175)
E/AndroidRuntime(31015): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(31015): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(31015): 	at android.os.Looper.loop(Looper.java:238)
E/AndroidRuntime(31015): 	at android.app.ActivityThread.main(ActivityThread.java:7824)
E/AndroidRuntime(31015): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31015): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(31015): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
I/Process (31015): Sending signal. PID: 31015 SIG: 9
Lost connection to device.

**Comment by adimunawar** [comment]
same issue

**Comment by RJIOSDEV** [comment]
rear camera video output video is green screen.

**Comment by Tapendra-Bista** [comment]
same issue 🥲
